In [24]:
from torchvision import datasets
import torchvision.transforms as transforms


def get_dataset(dataset_name, path='database'):
    if dataset_name in ['amazon', 'dslr', 'webcam']:  # OFFICE-31
        data_transforms = {
            'train': transforms.Compose([
                transforms.Resize([256, 256]),
                transforms.RandomCrop(224),
                transforms.RandomHorizontalFlip(),
                transforms.ToTensor(),
                transforms.Normalize([0.485, 0.456, 0.406], [0.229, 0.224, 0.225])
            ]),
            'test': transforms.Compose([
                transforms.Resize([224, 224]),
                transforms.CenterCrop((224, 224)),
                transforms.ToTensor(),
                transforms.Normalize([0.485, 0.456, 0.406], [0.229, 0.224, 0.225])
            ]),
        }
        print(path + '/office31/' + dataset_name + '/')
        tr_dataset = datasets.ImageFolder(path + '/office31/' + dataset_name + '/', data_transforms['train'])
        te_dataset = datasets.ImageFolder(path + '/office31/' + dataset_name + '/', data_transforms['test'])
        print('{} train set size: {}'.format(dataset_name, len(tr_dataset)))
        print('{} test set size: {}'.format(dataset_name, len(te_dataset)))

    else:
        raise ValueError('Dataset %s not found!' % dataset_name)
    return tr_dataset, te_dataset

In [25]:
src_trainset, src_testset = get_dataset('amazon')

database/office31/amazon/
amazon train set size: 2817
amazon test set size: 2817


In [26]:
src_trainset

Dataset ImageFolder
    Number of datapoints: 2817
    Root location: database/office31/amazon/
    StandardTransform
Transform: Compose(
               Resize(size=[256, 256], interpolation=bilinear, max_size=None, antialias=None)
               RandomCrop(size=(224, 224), padding=None)
               RandomHorizontalFlip(p=0.5)
               ToTensor()
               Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225])
           )

In [154]:
x = torch.Tensor([[0.2, 0.2, 1.5, 0.3, 0.3]])

In [155]:
x

tensor([[0.2000, 0.2000, 1.5000, 0.3000, 0.3000]])

In [156]:
import torch
import torch.nn.functional as F

In [157]:
k =F.softmax(x, dim=1)

In [158]:
k

tensor([[0.1269, 0.1269, 0.4657, 0.1403, 0.1403]])

In [159]:
s =F.softmax(x/2, dim=1)

In [160]:
i

tensor([[0.1754, 0.1754, 0.2616, 0.1938, 0.1938]])

In [161]:
1 - i

tensor([[0.8246, 0.8246, 0.7384, 0.8062, 0.8062]])

In [142]:
k =F.softmax(x/2, dim=1)

In [143]:
k

tensor([[0.1878, 0.1878, 0.2294, 0.1975, 0.1975]])

In [94]:
torch.topk(F.softmax(x, dim=1), k=1)

torch.return_types.topk(
values=tensor([[0.2616]]),
indices=tensor([[2]]))

In [125]:
a = torch.tensor([[0.5, 0.4], [0.6, 0.3]])

In [126]:
b = torch.tensor([[0.4, 0.7], [0.7, 0.7]])

In [127]:
torch.ge(b, a)

tensor([[False,  True],
        [ True,  True]])

In [128]:
a = torch.nonzero(torch.ge(b, a)).squeeze()

In [129]:
a

tensor([[0, 1],
        [1, 0],
        [1, 1]])

In [130]:
a.dim()

2

In [131]:
a.numel()

6